import test from 'node:test';
import assert from 'node:assert/strict';
import {flowerFixture, source, patientRenderer} from './patient-flower-fixture.mjs';
import {renderParentPortalSpecialist} from '../parent-specialist.js';
const tabSource=source.slice(source.indexOf('function renderTab('),source.indexOf('\ninit().catch('));
const goalsSource=source.slice(source.indexOf('function goalsHtml('),source.indexOf('function renderPatient('));
async function settleReads(){for(let i=0;i<40;i++)await Promise.resolve();}
async function harness({tab='overview',contacts=[],goals=[]}={}){
 const f=await flowerFixture(),{env,document,window,state}=f;
 Object.assign(env,{FormData:window.FormData,crypto:globalThis.crypto,renderParentPortalSpecialist,enableVoiceInput(){},watchFormDirty(){},toleranceLabel:()=>'',setButtonSaving(){},setButtonSaved(){},setButtonError(){},sleep:async()=>{}});
 Object.assign(state,{tab,contacts,goals});const writes=[];let onWrite=()=>{};
 env.sb={from(table){let op='read',payload,one=false;const q=new Proxy({then(resolve){if(op!=='read'){const call={table,op,payload};writes.push(call);onWrite(call);}const rows=table==='patient_contacts'?state.contacts:[];return Promise.resolve({data:one?(rows[0]||{id:'synthetic-write'}):rows,error:null}).then(resolve);}},{get(t,k){return t[k]||((...args)=>{if(k==='single')one=true;if(['insert','update','delete'].includes(k)){op=k;payload=args[0];}return q;});}});return q;}};
 const render=new Function('env',`with(env){${goalsSource}\n${patientRenderer}\n${tabSource}\nreturn renderPatient;}`)(env);
 return {...f,writes,render,setWriteHook(fn){onWrite=fn;},async navigate(section){await document.querySelector(`[data-tab="${section}"]`).onclick();}};
}
test('existing contact edit remains an update across section navigation',async()=>{
 const h=await harness({contacts:[{id:'contact-original',full_name:'Original Parent',patient_id:'child-a',therapist_id:'owner'}]});
 try{h.render();h.document.querySelector('[data-edit-contact]').click();const form=h.document.getElementById('contactForm');form.elements.full_name.value='Edited Parent';const submit=form.onsubmit;await h.navigate('goals');await h.navigate('overview');assert.equal(form,h.document.getElementById('contactForm'));assert.equal(form.elements.full_name.value,'Edited Parent');await form.onsubmit({preventDefault(){}});const writes=h.writes.filter(c=>c.table==='patient_contacts');assert.equal(writes.length,1);assert.equal(writes[0].op,'update',`Existing contact became an insert; retained handler=${submit===form.onsubmit}`);}finally{await h.close();}
});
test('session save refreshes cached goal cards while preserving the goal editor draft',async()=>{
 const h=await harness({goals:[{id:'g',patient_id:'child-a',title:'Test goal',progress:35,status:'active'}]});
 try{let saved=false;h.setWriteHook(c=>{if(c.table==='sessions'&&c.op==='insert')saved=true;});h.env.loadPatientData=async()=>{if(saved)h.state.goals=[{...h.state.goals[0],progress:55}];};h.render();await h.navigate('goals');assert.equal(h.document.querySelector('.goal-pct').textContent,'35%');h.document.querySelector('#goalFormToggle').click();const goalForm=h.document.getElementById('goalForm');goalForm.elements.title.value='Несохранённая вымышленная цель';await h.navigate('sessions');const form=h.document.getElementById('sessionForm');form.elements.note.value='Session';await form.onsubmit({target:form,preventDefault(){}});await h.navigate('goals');assert.equal(h.state.goals[0].progress,55);assert.equal(h.document.querySelector('.goal-pct').textContent,'55%');assert.equal(h.document.getElementById('goalForm'),goalForm);assert.equal(goalForm.elements.title.value,'Несохранённая вымышленная цель');assert.equal(goalForm.hidden,false);}finally{await h.close();}
});
test('cached Parent receives an Overview contact and retains its own new-contact draft',async()=>{
 const h=await harness({tab:'parent'});
 try{h.setWriteHook(c=>{if(c.table==='patient_contacts'&&c.op==='insert')h.state.contacts=[{...c.payload,id:'new-contact'}];});h.render();await settleReads();await h.document.querySelector('[data-add-parent]').onclick();const draft=h.document.querySelector('[data-parent-contact-form]');draft.elements.full_name.value='Другой несохранённый контакт';await h.navigate('overview');h.document.querySelector('#addContactBtn').click();const form=h.document.getElementById('contactForm');form.elements.full_name.value='New Parent';form.elements.email.value='parent@example.test';await form.onsubmit({preventDefault(){}});await h.navigate('parent');await settleReads();assert.equal(h.state.contacts.length,1);assert.equal(h.document.querySelectorAll('.parent-specialist-contacts .parent-contact').length,1);assert.match(h.document.querySelector('.parent-specialist-contacts').textContent,/New Parent/);assert.equal(h.document.querySelector('[data-parent-contact-form]'),draft);assert.equal(draft.elements.full_name.value,'Другой несохранённый контакт');assert.equal(draft.hidden,false);}finally{await h.close();}
});
test('cached Overview receives a Parent contact without resetting its contact edit identity',async()=>{
 const h=await harness({contacts:[{id:'original',full_name:'Original Parent',email:'original@example.test',patient_id:'child-a',therapist_id:'owner'}]});
 try{h.setWriteHook(c=>{if(c.table==='patient_contacts'&&c.op==='insert')h.state.contacts.push({...c.payload,id:'added-parent'});});h.render();h.document.querySelector('[data-edit-contact]').click();const overviewForm=h.document.getElementById('contactForm');overviewForm.elements.full_name.value='Несохранённое изменение';await h.navigate('parent');await settleReads();await h.document.querySelector('[data-add-parent]').onclick();const form=h.document.querySelector('[data-parent-contact-form]');form.elements.full_name.value='Added in Parent';form.elements.relation.value='Мать';form.elements.email.value='added@example.test';await form.onsubmit({preventDefault(){}});await h.navigate('overview');assert.equal(h.document.querySelectorAll('[data-edit-contact]').length,2);assert.equal(h.document.getElementById('contactForm'),overviewForm);assert.equal(overviewForm.elements.full_name.value,'Несохранённое изменение');await overviewForm.onsubmit({preventDefault(){}});assert.equal(h.writes.filter(c=>c.table==='patient_contacts').at(-1).op,'update');}finally{await h.close();}
});

test('Parent contact-list refresh preserves an unsaved email field and its handler',async()=>{
 const h=await harness({tab:'parent',contacts:[{id:'original',full_name:'Original Parent',email:'original@example.test',patient_id:'child-a',therapist_id:'owner'}]});
 try{h.render();await settleReads();const input=h.document.querySelector('[data-contact="original"] [name=email]');input.value='unsaved@example.test';input.dispatchEvent(new h.window.Event('input'));const handler=input.oninput;h.setWriteHook(c=>{if(c.table==='patient_contacts'&&c.op==='insert')h.state.contacts.push({...c.payload,id:'added-contact'});});await h.navigate('overview');h.document.querySelector('#addContactBtn').click();const form=h.document.getElementById('contactForm');form.elements.full_name.value='New Parent';form.elements.email.value='new@example.test';await form.onsubmit({preventDefault(){}});await h.navigate('parent');await settleReads();assert.equal(h.document.querySelectorAll('.parent-specialist-contacts .parent-contact').length,2);assert.equal(h.document.querySelector('[data-contact="original"] [name=email]'),input);assert.equal(input.value,'unsaved@example.test');assert.equal(input.oninput,handler);assert.equal(h.document.querySelector('[data-contact="original"] [data-invite]').disabled,true);}finally{await h.close();}
});
