import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { Window } from 'happy-dom';
import { createParentPortal } from '../parent.js';
import { createSpecialistRoleGate } from '../role-gate.mjs';
const identitySql=readFileSync(new URL('../supabase/migrations/20261003_008_parent_portal_identity.sql',import.meta.url),'utf8');
const invitationFlows=[...identitySql.match(/auth_flow text not null check \(auth_flow in \(([^)]+)\)\)/)[1].matchAll(/'([^']+)'/g)].map(match=>match[1]);
const CHILD='11111111-1111-4111-8111-111111111111', OTHER='22222222-2222-4222-8222-222222222222', REPORT='33333333-3333-4333-8333-333333333333', MEDIA='44444444-4444-4444-8444-444444444444';
const wait=()=>new Promise(r=>setTimeout(r,10));
function setup({invite=false,flow='new',children=[{id:CHILD,display_name:'Маша',date_of_birth:'2020-01-01'}],rpc,functions,user={id:'parent',email:'p@example.com',user_metadata:{full_name:'Мама'}}}={}) {
 const window=new Window({url:`https://fizira.com/parent.html${invite?'?invite=private-token':''}`}); window.document.body.innerHTML='<main id="app"></main>';
 const calls=[],updates=[];let callback;
 const sb={from(){throw Error('Source table forbidden')},rpc:async(name,args)=>{calls.push([name,args]);if(rpc){const result=await rpc(name,args);if(result!==undefined)return result;}return {data:name==='parent_invitation_state'?{state:'valid',auth_flow:flow}:name==='current_app_roles'?[{role:'parent'}]:name==='parent_portal_children'?children:name==='parent_portal_dashboard'?{child:children.find(c=>c.id===args.p_patient_id),schedule:[],reports:[],goals:[],notifications:[],dynamics:[]}:name==='parent_portal_report'?{report:{id:REPORT,kind:'session',snapshot:{what_did:'<img src=x onerror=alert(1)>'},media_ids:[MEDIA]}}:[]}},functions:{invoke:async(name,args)=>{calls.push([name,args]);return functions?functions(name,args):{data:{url:'https://auth.fizira.com/storage/v1/object/sign/patient-media/file?token=signed'}}}},auth:{getSession:async()=>({data:{session:user?{user}:null}}),onAuthStateChange(fn){callback=fn;return {data:{subscription:{unsubscribe(){}}}}},updateUser:async(data)=>{updates.push(data);return {data:{user:{...user,user_metadata:{...user?.user_metadata,...data.data}}}}},signOut:async()=>{callback('SIGNED_OUT',null);return {}},signInWithPassword:async()=>({}),resetPasswordForEmail:async()=>({})}};
 const app=window.document.getElementById('app'); const portal=createParentPortal({app,sb,window,document:window.document});return {window,app,sb,portal,calls,updates,event:(...args)=>callback(...args)};
}
function fill(app,name,value){app.querySelector(`[name="${name}"]`).value=value;}
async function submit(app,id){app.querySelector(id).dispatchEvent(new app.ownerDocument.defaultView.Event('submit',{bubbles:true,cancelable:true}));await wait();}
function legal(app){app.querySelectorAll('[name="legal"]').forEach(i=>i.checked=true);}
test('mobile entry has no referrer and dashboard uses only narrow RPCs',async()=>{const h=setup();await h.portal.start();assert.match(h.app.textContent,/Ближайшее занятие/);assert.match(h.app.textContent,/Главная.*Расписание.*Отчёты.*Цели.*Динамика/s);assert.match(readFileSync(new URL('../parent.html',import.meta.url),'utf8'),/name="referrer" content="no-referrer"/);assert.equal(h.calls[0][0],'current_app_roles');});
test('new invitation requires matching password, name and three exact legal checks; update precedes acceptance',async()=>{const h=setup({invite:true});await h.portal.start();assert.deepEqual(h.calls.map(c=>c[0]),['parent_invitation_state']);fill(h.app,'full_name','Мама');fill(h.app,'password','secure-password');fill(h.app,'confirm','different');legal(h.app);await submit(h.app,'#inviteForm');assert.equal(h.updates.length,0);fill(h.app,'confirm','secure-password');await submit(h.app,'#inviteForm');assert.equal(h.updates[0].password,'secure-password');const accepted=h.calls.find(c=>c[0]==='accept_parent_invitation');assert.deepEqual(accepted[1].p_accepted_documents,[{document_type:'terms',accepted:true},{document_type:'privacy',accepted:true},{document_type:'personal_data_consent',accepted:true}]);assert.doesNotMatch(h.window.location.href,/invite=/);});
test('existing account accepts with blank password',async()=>{const h=setup({invite:true,flow:'existing'});await h.portal.start();legal(h.app);await submit(h.app,'#inviteForm');assert.equal(h.updates[0].password,undefined);assert.doesNotMatch(h.window.location.href,/invite=/);});
test('invalid invitation never loads child/source data or provider errors',async()=>{const h=setup({invite:true,rpc:n=>n==='parent_invitation_state'?{data:{state:'expired'}}:undefined});await h.portal.start();assert.match(h.app.textContent,/Приглашение недоступно/);assert.doesNotMatch(h.app.textContent,/private-token/);assert.deepEqual(h.calls.map(c=>c[0]),['parent_invitation_state']);});
test('child switching discards stale requests',async()=>{let resolve;const h=setup({children:[{id:CHILD,display_name:'Маша'},{id:OTHER,display_name:'Петя'}],rpc:(n,a)=>n==='parent_portal_schedule'&&a.p_patient_id===CHILD?new Promise(r=>resolve=r):undefined});await h.portal.start();const pending=h.portal.navigate('schedule');await wait();await h.portal.selectChild(OTHER);resolve({data:[{starts_at:'2026-10-03T10:00Z',status:'old-child-secret'}]});await pending;assert.doesNotMatch(h.app.textContent,/old-child-secret/);assert.match(h.app.textContent,/Петя/);});
test('empty children and retry errors are plain and safe',async()=>{const h=setup({children:[]});await h.portal.start();assert.match(h.app.textContent,/Нет доступных детей/);const e=setup({rpc:n=>n==='parent_portal_children'?{error:{message:'provider-secret'}}:undefined});await e.portal.start();assert.match(e.app.textContent,/Повторить/);assert.doesNotMatch(e.app.textContent,/provider-secret/);});
test('sections use actual RPC parameters, both schedule modes and safe dynamics',async()=>{const h=setup({rpc:n=>n==='parent_portal_dynamics'?{data:[{scale:'hine',assessed_at:'2026-10-01',value_numeric:20},{scale:'gmfcs',assessed_at:'2026-10-01',value_text:'II'}]}:undefined});await h.portal.start();for(const section of ['schedule','reports','goals','dynamics'])await h.portal.navigate(section);assert.match(h.app.textContent,/hine/i);assert.match(h.app.textContent,/II/);assert.ok(h.calls.some(c=>c[0]==='parent_portal_schedule'&&c[1].p_mode==='upcoming'));await h.portal.navigate('schedule');h.app.querySelector('[data-mode="history"]').click();await wait();assert.ok(h.calls.some(c=>c[1]?.p_mode==='history'));});
test('unread notifications mark on explicit action',async()=>{const h=setup({rpc:n=>n==='parent_portal_dashboard'?{data:{child:{id:CHILD},notifications:[{id:MEDIA,title:'Новый отчёт',read_at:null}]}}:undefined});await h.portal.start();h.app.querySelector('[data-read]').click();await wait();assert.ok(h.calls.some(c=>c[0]==='parent_mark_notifications_read'&&c[1].p_notification_ids[0]===MEDIA));});
test('report escapes fields and validates photo and PDF endpoint URLs',async()=>{const h=setup();await h.portal.start();await h.portal.openReport(REPORT);assert.equal(h.app.querySelector('[onerror]'),null);const r=await h.portal.invokeFile('photo',REPORT,MEDIA);assert.equal(r.name,'parent-report-file');assert.match(r.url,/^https:\/\/auth.fizira.com\/storage\/v1\/object\/sign\/patient-media\//);assert.equal((await h.portal.invokeFile('pdf',REPORT)).name,'parent-report-file');for(const url of ['https://evil.com/file','https://auth.fizira.com/other','http://auth.fizira.com/storage/v1/object/sign/patient-media/file','https://u:p@auth.fizira.com/storage/v1/object/sign/patient-media/file']){h.sb.functions.invoke=async()=>({data:{url}});await assert.rejects(h.portal.invokeFile('photo',REPORT,MEDIA));}h.app.querySelector('[data-photo]').click();await wait();assert.match(h.app.textContent,/Фото недоступно/);assert.equal(h.app.querySelector('[data-photo]').disabled,true);});
test('profile and password updates, focus preservation and logout cancel child work',async()=>{let resolve;const h=setup({rpc:n=>n==='parent_portal_goals'?new Promise(r=>resolve=r):undefined});await h.portal.start();await h.portal.navigate('profile');fill(h.app,'full_name','Новое имя');h.event('TOKEN_REFRESHED',{user:{id:'parent'}});h.event('SIGNED_IN',{user:{id:'parent'}});await wait();assert.equal(h.app.querySelector('[name="full_name"]').value,'Новое имя');await submit(h.app,'#profileForm');assert.equal(h.updates[0].data.full_name,'Новое имя');fill(h.app,'password','new-password');fill(h.app,'confirm','new-password');await submit(h.app,'#passwordForm');assert.equal(h.updates[1].password,'new-password');const pending=h.portal.navigate('goals');await wait();await h.portal.logout();resolve({data:[{title:'private-old-data'}]});await pending;assert.match(h.app.textContent,/Вход для родителей/);assert.doesNotMatch(h.app.textContent,/private-old-data/);});
test('returning parent login and password recovery screens are usable',async()=>{const h=setup({user:null});await h.portal.start();assert.ok(h.app.querySelector('#loginForm'));h.app.querySelector('#recoverBtn').click();assert.ok(h.app.querySelector('#recoveryForm'));h.event('PASSWORD_RECOVERY',{user:{id:'parent'}});await wait();assert.ok(h.app.querySelector('#passwordForm'));});
test('actual specialist role gate redirects parent, supports dual role, and fails closed',async()=>{for(const roles of [[{role:'parent'}],[{role:'specialist'},{role:'parent'}],[],null]){const events=[];const gate=createSpecialistRoleGate({sb:{rpc:async()=>({data:roles})},setReady:v=>events.push(['ready',v]),redirect:p=>events.push(['redirect',p])});if(roles===null){await assert.rejects(gate.loadCurrentRoles());assert.equal(gate.canNavigate(),false);continue;}const result=await gate.loadCurrentRoles();assert.equal(gate.canNavigate(),roles?.some(r=>r.role==='specialist')||false);if(roles?.length===1)assert.ok(events.some(e=>e[0]==='redirect'&&e[1]==='parent.html'));assert.equal(result.has('parent'),Boolean(roles?.some(r=>r.role==='parent')));gate.reset();assert.equal(gate.canNavigate(),false);}const gate=createSpecialistRoleGate({sb:{rpc:async()=>({error:{message:'private'}})},setReady(){},redirect(){}});await assert.rejects(gate.loadCurrentRoles(),/Не удалось проверить доступ/);assert.equal(gate.canNavigate(),false);});
test('specialist bootstrap gate precedes consent/profile/patients and shell visibility respects it',()=>{const source=readFileSync(new URL('../app.js',import.meta.url),'utf8');const view=source.slice(source.indexOf('async function renderAuthView'),source.indexOf('function scheduleAuthView'));assert.ok(view.indexOf('await loadCurrentRoles()')<view.indexOf('await ensureUserConsentRecord()'));assert.match(source,/window\.fiziraNavigate[\s\S]*?roleGate\.canNavigate\(\)/);assert.match(readFileSync(new URL('../index.html',import.meta.url),'utf8'),/specialistReady/);});
test('executes real specialist bootstrap with parent-only, dual, empty and failed roles',async()=>{
 const source=readFileSync(new URL('../app.js',import.meta.url),'utf8');const view=source.slice(source.indexOf('async function renderAuthView'),source.indexOf('function scheduleAuthView'));
 for(const rows of [[{role:'parent'}],[{role:'specialist'},{role:'parent'}],[],null]){
  const window=new Window({url:'https://fizira.com/index.html'});window.document.body.innerHTML='<main id="app"></main><div id="headerActions"></div>';const calls=[];
  const env={authViewRevision:1,passwordRecoveryActive:false,user:{id:'u'},state:{profile:{full_name:'Name',profession:'Therapist'}},document:window.document,app:window.document.getElementById('app'),headerActions:window.document.getElementById('headerActions'),currentRoles:new Set(),renderHeader(){},ensureUserConsentRecord:async()=>calls.push('consent'),loadProfile:async()=>calls.push('profile'),isSpecialistProfileComplete:()=>true,loadPatients:async()=>calls.push('patients'),renderPatients:async()=>calls.push('render'),sb:{auth:{signOut:async()=>({})}}};
  env.roleGate=createSpecialistRoleGate({sb:{rpc:async()=>({data:rows,error:rows===null?{}:null})},setReady(){},redirect:p=>calls.push(p)});env.loadCurrentRoles=async()=>{calls.push('roles');return env.currentRoles=await env.roleGate.loadCurrentRoles();};
  const render=new Function('env',`with(env) { return (${view}); }`)(env);await render(1);
  if(rows?.some(r=>r.role==='specialist')){assert.deepEqual(calls,['roles','consent','profile','patients','render']);assert.equal(env.headerActions.querySelector('a').getAttribute('href'),'parent.html');}else{assert.equal(calls.includes('consent'),false);assert.equal(calls.includes('profile'),false);assert.equal(calls.includes('patients'),false);}
 }
});
test('account switch cancels old child data and rechecks new account roles',async()=>{let resolve;const h=setup({rpc:n=>n==='parent_portal_goals'?new Promise(r=>resolve=r):undefined});await h.portal.start();const pending=h.portal.navigate('goals');await wait();h.event('SIGNED_IN',{user:{id:'other-parent'}});await wait();resolve({data:[{title:'prior-account-secret'}]});await pending;assert.doesNotMatch(h.app.textContent,/prior-account-secret/);assert.equal(h.calls.filter(c=>c[0]==='current_app_roles').length,2);});
test('invitation rejects unchecked legal and missing name, and update failure never accepts',async()=>{const h=setup({invite:true});await h.portal.start();fill(h.app,'full_name','');fill(h.app,'password','safe-password');fill(h.app,'confirm','safe-password');legal(h.app);await submit(h.app,'#inviteForm');assert.equal(h.updates.length,0);fill(h.app,'full_name','Мама');h.app.querySelector('[name="legal"]').checked=false;await submit(h.app,'#inviteForm');assert.equal(h.updates.length,0);legal(h.app);h.sb.auth.updateUser=async()=>({error:{message:'token-secret'}});await submit(h.app,'#inviteForm');assert.equal(h.calls.some(c=>c[0]==='accept_parent_invitation'),false);assert.doesNotMatch(h.app.textContent,/token-secret/);assert.match(h.window.location.href,/invite=/);});
test('PDF download and photos use validated file responses and stale file never reappears',async()=>{let resolve;const h=setup();await h.portal.start();await h.portal.openReport(REPORT);let download;h.window.HTMLAnchorElement.prototype.click=function(){download={url:this.href,rel:this.rel,referrer:this.referrerPolicy};};h.app.querySelector('#downloadReport').click();await wait();assert.match(download.url,/auth\.fizira\.com\/storage\/v1\/object\/sign\/patient-media\//);assert.equal(download.referrer,'no-referrer');assert.deepEqual(h.calls.find(c=>c[0]==='parent-report-file')[1].body,{kind:'pdf',report_id:REPORT});h.sb.functions.invoke=()=>new Promise(r=>resolve=r);h.app.querySelector('[data-photo]').click();await wait();await h.portal.navigate('goals');resolve({data:{url:'https://auth.fizira.com/storage/v1/object/sign/patient-media/photo?token=signed'}});await wait();assert.equal(h.app.querySelector('img'),null);assert.doesNotMatch(h.app.textContent,/Фото/);});
test('unknown section cannot dispatch an unrestricted RPC',async()=>{const h=setup();await h.portal.start();const calls=h.calls.length;await h.portal.navigate('clinical_source');assert.equal(h.calls.length,calls);});
test('notification marking refreshes authoritative notification state',async()=>{const h=setup({rpc:n=>n==='parent_portal_dashboard'?{data:{child:{id:CHILD},notifications:[{id:MEDIA,title:'Новости',read_at:null}]}}:n==='parent_mark_notifications_read'?{data:1}:n==='parent_portal_notifications'?{data:[{id:MEDIA,read_at:'2026-10-03'}]}:undefined});await h.portal.start();h.app.querySelector('[data-read]').click();await wait();assert.match(h.app.querySelector('[data-read]').textContent,/Прочитано/);assert.ok(h.calls.some(c=>c[0]==='parent_portal_notifications'&&c[1].p_patient_id===CHILD));});
test('parent layout overrides specialist auth flex and width at mobile and desktop',()=>{const h=setup();h.window.document.body.className='parent-portal';const style=h.window.document.createElement('style');style.textContent=readFileSync(new URL('../styles.css',import.meta.url),'utf8')+'\n'+readFileSync(new URL('../parent.css',import.meta.url),'utf8');h.window.document.head.append(style);for(const width of [390,1024]){h.window.happyDOM.setWindowSize({width,height:844});const computed=h.window.getComputedStyle(h.app);assert.equal(computed.display,'block');assert.equal(computed.maxWidth,'1000px');}});

test('invitation flows come from actual migration008 enum',async()=>{assert.deepEqual(invitationFlows,['new','existing']);for(const flow of invitationFlows){const h=setup({invite:true,flow});await h.portal.start();assert.ok(h.app.querySelector('#inviteForm'));assert.equal(h.app.querySelector('[name="password"]').required,flow==='new');legal(h.app);if(flow==='new'){await submit(h.app,'#inviteForm');assert.equal(h.updates.length,0);fill(h.app,'password','new-password');fill(h.app,'confirm','new-password');}await submit(h.app,'#inviteForm');assert.ok(h.calls.some(c=>c[0]==='accept_parent_invitation'));}});
test('appointment rows use Moscow date and clock across UTC midnight without changing DOB or assessment semantics',async()=>{const prior=process.env.TZ;process.env.TZ='Europe/Moscow';try{const appointment={starts_at:'2026-10-02T21:30:00Z',ends_at:'2026-10-02T22:30:00Z',status:'scheduled'};const h=setup({rpc:n=>n==='parent_portal_dashboard'?{data:{child:{id:CHILD},schedule:[appointment],dynamics:[{scale:'hine',assessed_at:'2026-10-02',value_numeric:30}]}}:n==='parent_portal_schedule'?{data:[appointment]}:undefined});await h.portal.start();const row=h.app.querySelector('#parentContent .item');assert.match(row.textContent,/3 октября 2026/);assert.match(row.textContent,/00:30.*01:30/);assert.match(h.app.textContent,/2 октября 2026/);assert.match(h.app.textContent,/6 лет 9 мес/);await h.portal.navigate('schedule');assert.match(h.app.querySelector('.item').textContent,/3 октября 2026.*00:30/s);}finally{if(prior===undefined)delete process.env.TZ;else process.env.TZ=prior;}});
function rootTransitionHarness(){
 const source=readFileSync(new URL('../app.js',import.meta.url),'utf8');const window=new Window({url:'https://fizira.com/index.html'});window.document.body.innerHTML='<main id="app"><button id="addPatient">Добавить ребёнка</button><p>old-child-secret</p></main><div id="headerActions"></div>';let authCallback,resolveRole;const fromCalls=[];
 const sb={rpc:()=>new Promise(r=>resolveRole=r),from(table){fromCalls.push(table);return {insert(){return this},select(){return this},single:async()=>({error:{message:'test write blocked'}})};},auth:{onAuthStateChange(callback){authCallback=callback;},getSession:async()=>{authCallback('SIGNED_IN',{user:{id:'specialist'}});return {data:{session:{user:{id:'specialist'}}}};},signOut:async()=>({})}};
 const env={window,document:window.document,app:window.document.getElementById('app'),headerActions:window.document.getElementById('headerActions'),sb,user:{id:'specialist'},session:null,state:{patients:[{id:CHILD,display_name:'old-child-secret'}]},createEmptyState:()=>({patients:[]}),currentRoles:new Set(['specialist']),authViewRevision:0,passwordRecoveryActive:false,setPasswordRecovery(active){env.passwordRecoveryActive=active;},shouldRenderAuthEvent:(event,previous,next)=>event==='SIGNED_OUT'||previous!==next,renderHeader(){},renderLogin(){env.app.textContent='login';},renderUpdatePassword(){},ensureUserConsentRecord:async()=>{},loadProfile:async()=>{},isSpecialistProfileComplete:()=>true,loadPatients:async()=>{},renderPatients:async()=>{},renderProfile(){},loadPatientData:async()=>{},renderPatient(){},watchFormDirty(){},setButtonSaving(){},setButtonError(){},setButtonSaved(){},sleep:async()=>{},FormData:window.FormData,flash(){},setTimeout:window.setTimeout.bind(window)};
 env.roleGate=createSpecialistRoleGate({sb:{rpc:async()=>({data:[{role:'specialist'}]})},setReady(){},redirect(){}});
 function compile(start,end){return new Function('env',`with(env){return (${source.slice(source.indexOf(start),source.indexOf(end,source.indexOf(start)))});}`)(env);}
 env.renderNewPatient=compile('function renderNewPatient()', 'const currentPatient');env.renderAuthView=compile('async function renderAuthView(', 'function scheduleAuthView(');env.scheduleAuthView=compile('function scheduleAuthView(', 'async function init()');const init=compile('async function init()', 'function authIdentity()');env.loadCurrentRoles=()=>env.roleGate.loadCurrentRoles();
 env.app.querySelector('#addPatient').onclick=env.renderNewPatient;
 return {env,init,fromCalls,event(name){authCallback(name,{user:{id:env.user.id}});},get oldButton(){return env.app.querySelector('#addPatient');},compile,change(id){authCallback(id?'SIGNED_IN':'SIGNED_OUT',id?{user:{id}}:null);},resolveRole(){resolveRole?.({data:[{role:'parent'}]});}};
}
test('real root account switch synchronously retires old specialist action DOM before delayed roles',async()=>{const h=rootTransitionHarness();await h.env.roleGate.loadCurrentRoles();await h.init();const oldButton=h.oldButton;oldButton.click();const form=h.env.app.querySelector('#patientForm'),submit=form.onsubmit;form.elements.display_name.value='old-child';h.change('parent');assert.equal(h.env.roleGate.canNavigate(),false);assert.ok(!h.env.app.querySelector('#patientForm'),'previous specialist form is retired');assert.doesNotMatch(h.env.app.textContent,/old-child-secret/);oldButton.click();assert.ok(!h.env.app.querySelector('#patientForm'),'previous specialist form is retired');await submit({preventDefault(){},target:form});assert.equal(h.fromCalls.length,0);await wait();});
test('root same-account token refresh and repeated sign-in preserve specialist unsaved form',async()=>{const h=rootTransitionHarness();await h.env.roleGate.loadCurrentRoles();await h.init();h.oldButton.click();const form=h.env.app.querySelector('#patientForm');form.elements.display_name.value='unsaved';h.change('specialist');assert.equal(h.env.app.querySelector('#patientForm'),form);assert.equal(form.elements.display_name.value,'unsaved');});

test('pending real patient list renderer stops after identity switch before another data call or DOM restoration',async()=>{const h=rootTransitionHarness();await h.env.roleGate.loadCurrentRoles();await h.init();let resolveCounts,activityCalls=0;h.env.countsForPatients=()=>new Promise(r=>resolveCounts=r);h.env.activityForPatients=async()=>{activityCalls++;return {};};const render=h.compile('async function renderPatients()', 'function renderNewPatient()');const pending=render();h.change('parent');resolveCounts({});await pending;assert.equal(activityCalls,0);assert.doesNotMatch(h.env.app.textContent,/old-child-secret/);});
test('signout synchronously retires specialist DOM and detached form action',async()=>{const h=rootTransitionHarness();await h.env.roleGate.loadCurrentRoles();await h.init();h.oldButton.click();const form=h.env.app.querySelector('#patientForm'),submit=form.onsubmit;h.change(null);assert.ok(!h.env.app.querySelector('#patientForm'));await submit({preventDefault(){},target:form});assert.equal(h.fromCalls.length,0);await wait();assert.equal(h.env.app.textContent,'login');});
test('actual appointment and publication goal statuses render human labels',async()=>{const scheduleSql=readFileSync(new URL('../supabase/migrations/20260923_005_specialist_schedule.sql',import.meta.url),'utf8'),publicationSql=readFileSync(new URL('../supabase/migrations/20261003_009_parent_portal_publications.sql',import.meta.url),'utf8');assert.match(scheduleSql,/status in \('planned', 'completed', 'cancelled', 'no_show'\)/);assert.match(publicationSql,/status in \('new','in_progress','achieved','revised'\)/);const h=setup({rpc:n=>n==='parent_portal_schedule'?{data:['planned','completed','cancelled','no_show'].map(status=>({starts_at:'2026-10-03T10:00Z',ends_at:'2026-10-03T11:00Z',status}))}:n==='parent_portal_goals'?{data:['new','in_progress','achieved','revised'].map(status=>({title:status,status}))}:undefined});await h.portal.start();await h.portal.navigate('schedule');for(const label of ['Запланировано','Проведено','Отменено','Неявка'])assert.match(h.app.textContent,new RegExp(label));await h.portal.navigate('goals');assert.deepEqual([...h.app.querySelectorAll('.goal .badge')].map(el=>el.textContent),['Новая','В работе','Достигнута','Пересмотрена']);});
test('mobile navigation stays at bottom with content clearance; desktop remains top; parent CSS leaves specialist layout unchanged',async()=>{const h=setup();await h.portal.start();const style=h.window.document.createElement('style');style.textContent=readFileSync(new URL('../styles.css',import.meta.url),'utf8');h.window.document.head.append(style);const properties=['display','maxWidth','paddingTop','paddingBottom','backgroundColor'];const specialistBefore=properties.map(p=>h.window.getComputedStyle(h.app)[p]);style.textContent+='\n'+readFileSync(new URL('../parent.css',import.meta.url),'utf8');assert.deepEqual(properties.map(p=>h.window.getComputedStyle(h.app)[p]),specialistBefore);h.window.document.body.className='parent-portal';for(const width of [320,390,759]){h.window.happyDOM.setWindowSize({width,height:844});style.textContent=style.textContent;const nav=h.window.getComputedStyle(h.app.querySelector('.parent-nav'));assert.equal(nav.position,'fixed');assert.equal(nav.bottom,'0px');assert.ok(parseFloat(h.window.getComputedStyle(h.app).paddingBottom)>=90);}h.window.happyDOM.setWindowSize({width:1024,height:844});style.textContent=style.textContent;assert.notEqual(h.window.getComputedStyle(h.app.querySelector('.parent-nav')).position,'fixed');});

test('real stale patient data loader cannot populate changed-account state; patient renderer fails closed while roles pending',async()=>{const h=rootTransitionHarness();await h.env.roleGate.loadCurrentRoles();await h.init();let resolve;const deferred=new Promise(r=>resolve=r);const query={select(){return this},eq(){return this},order(){return this},limit(){return this},then(...args){return deferred.then(...args);}};h.env.sb.from=()=>query;h.env.state.patientId=CHILD;const load=h.compile('async function loadPatientData()', 'function goalsHtml(');const pending=load();h.change('parent');const newState=h.env.state;resolve({data:[{id:CHILD,title:'old-child-secret'}]});await pending;assert.equal(h.env.state,newState);assert.deepEqual(h.env.state,{patients:[]});let patientReads=0;h.env.currentPatient=()=>{patientReads++;return {id:CHILD};};const render=h.compile('function renderPatient(', 'function option(');render();assert.equal(patientReads,0);assert.doesNotMatch(h.env.app.textContent,/old-child-secret/);});

test('same-account repeated password recovery keeps the existing password form',async()=>{const h=rootTransitionHarness();await h.env.roleGate.loadCurrentRoles();await h.init();h.env.app.innerHTML='<form id="updatePasswordForm"><input name="password" value="unsaved-password"></form>';const form=h.env.app.firstElementChild;h.event('PASSWORD_RECOVERY');assert.ok(h.env.app.firstElementChild===form);await wait();assert.equal(form.elements.password.value,'unsaved-password');});
function profileHarness(h){h.env.esc=value=>String(value??'');h.env.safeStorageUrl=value=>value;h.env.renderProfile=h.compile('function renderProfile()', 'async function loadPatients()');h.env.renderProfile();return h.env.app.querySelector('#profileForm');}
test('actual pending profile logo upload cannot upsert old fields or profile state after account switch',async()=>{const h=rootTransitionHarness();await h.env.roleGate.loadCurrentRoles();await h.init();let resolveUpload;const writes=[];h.env.sb.storage={from:()=>({upload:()=>new Promise(r=>resolveUpload=r)})};h.env.sb.from=table=>({upsert(payload){writes.push([table,payload]);return this;},select(){return this;},single:async()=>({data:{id:'parent',full_name:'OLD secret'}})});const form=profileHarness(h);form.elements.full_name.value='OLD secret';Object.defineProperty(h.env.app.querySelector('#profileLogoFile'),'files',{value:[new h.env.window.File(['photo'],'logo.png',{type:'image/png'})]});const pending=form.onsubmit({preventDefault(){}});await wait();h.change('parent');resolveUpload({});await pending;assert.equal(writes.length,0);assert.deepEqual(h.env.state,{patients:[]});});
test('real pending delete password dialog is cancelled on switch and cannot delete new account',async()=>{const h=rootTransitionHarness();await h.env.roleGate.loadCurrentRoles();await h.init();const calls=[];h.env.window.confirm=()=>true;h.env.window.prompt=()=>{calls.push('prompt');return 'УДАЛИТЬ';};h.env.sb.functions={invoke:async name=>{calls.push(name);return {data:{success:false}};}};profileHarness(h);const pending=h.env.app.querySelector('#deleteAccountBtn').onclick();const dialog=h.env.document.querySelector('.profile-delete-overlay');assert.ok(dialog);h.change('parent');assert.ok(!h.env.document.querySelector('.profile-delete-overlay'),'old account confirmation must close');await pending;assert.deepEqual(calls,[]);});
test('actual specialist photo preview overlay is retired synchronously on switch and signout',async()=>{for(const next of ['parent',null]){const h=rootTransitionHarness();await h.env.roleGate.loadCurrentRoles();await h.init();const source=readFileSync(new URL('../app.js',import.meta.url),'utf8');h.env.app.innerHTML='<div id="mediaList"><div data-media-card="photo"><button data-media-preview="https://auth.fizira.com/storage/v1/object/sign/patient-media/old.jpg" data-media-preview-kind="signed">Фото</button></div></div>';Object.assign(h.env,{mediaList:h.env.app.firstElementChild,availableItems:[{id:'photo',storage_path:'old-private-path'}],accountIsCurrent:()=>h.env.roleGate.canNavigate(),safeStorageUrl:x=>x,esc:x=>x,getPatientMediaObjectUrl:async()=>''});const start=source.indexOf("mediaList.querySelectorAll('[data-media-preview]')");const end=source.indexOf("mediaList.querySelectorAll('[data-delete-media]')",start);new Function('env',`with(env){${source.slice(start,end)}}`)(h.env);h.env.app.querySelector('[data-media-preview]').click();assert.ok(h.env.document.querySelector('.media-preview-overlay img'));h.change(next);assert.ok(!h.env.document.querySelector('.media-preview-overlay'),'old signed image must be removed');}});
