import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {Window} from 'happy-dom';
import {mountReportPdfExport} from '../report-pdf-export.mjs';
const source=readFileSync(new URL('../app.js',import.meta.url),'utf8');
test('actual consultation save enables PDF export without Parent Cabinet',async()=>{
 const window=new Window(),document=window.document;window.confirm=()=>true;
 document.body.innerHTML='<section id="parentReportEditor"><div id="parentReportPdfExport"></div><input id="reportTherapistName" value="Специалист">'+['Complaint','Strengths','Observations','Goals','Progress','Recommendations'].map(k=>`<textarea id="report${k}">Вымышленный текст</textarea>`).join('')+'</section>';
 const calls=[],rows=[];const env={window,document,mountReportPdfExport,parentReportEditor:document.getElementById('parentReportEditor'),saveParentReportPdfBtn:document.createElement('button'),editingParentReportId:null,accountIsCurrent:()=>true,user:{id:'specialist'},p:{id:'child'},state:{parentReports:rows,profile:{}},alert(){throw Error('unexpected')},setParentReportStatus(){},setTimeout(){},loadPatientData:async()=>{env.state.parentReports=rows},sb:{from(table){assert.equal(table,'parent_reports');let payload;const q={insert(v){payload=v;return q},select(){return q},single:async()=>{calls.push({table,payload});rows.push({...payload,id:'saved-report',publication_status:'draft'});return {data:{id:'saved-report'}}}};return q},functions:{invoke:async(name,{body})=>{calls.push({name,body});return {data:new Blob(['%PDF-1.7\nsynthetic'],{type:'application/pdf'})}}}}};
 const helperStart=source.indexOf('function mountOverviewPdfExport(');assert.ok(helperStart>=0);const helperEnd=source.indexOf('\nif (state.tab',helperStart);
 const saveStart=source.indexOf('if (saveParentReportPdfBtn) {'),saveEnd=source.indexOf("document\n  .querySelectorAll('[data-open-parent-report]')",saveStart);
 new Function('env',`with(env){${source.slice(helperStart,helperEnd)}\n${source.slice(saveStart,saveEnd)}}`)(env);
 try{await env.saveParentReportPdfBtn.onclick();const button=document.querySelector('[data-prepare-pdf]');assert.ok(button);await button.onclick();assert.equal(document.querySelector('[data-share-pdf]').disabled,false);assert.equal(rows.length,1);assert.equal(rows[0].publication_status,'draft');assert.deepEqual(calls.filter(c=>c.name).map(c=>c.name),['generate-parent-report-pdf']);assert.equal(calls.at(-1).body.mode,'export');
 document.getElementById('reportComplaint').value='Несохранённые изменения';document.getElementById('reportComplaint').dispatchEvent(new window.Event('input',{bubbles:true}));assert.equal(document.querySelector('[data-share-pdf]').disabled,true);await button.onclick();assert.match(document.getElementById('parentReportPdfExport').textContent,/Сначала сохраните/);assert.equal(calls.filter(c=>c.name).length,1);}finally{await window.happyDOM.abort();}
});
