import test from 'node:test';import assert from 'node:assert/strict';
import {parentPublicationHandler,digestBytes} from '../supabase/functions/_shared/parent-publication.ts';
const owner='11111111-1111-4111-8111-111111111111',child='22222222-2222-4222-8222-222222222222',id='33333333-3333-4333-8333-333333333333';
const bytes=new TextEncoder().encode('%PDF-1.7\nfictional report');
const request=extra=>new Request('https://edge.example.test',{method:'POST',headers:{origin:'https://app.fizira.com',authorization:'Bearer token','content-type':'application/json'},body:JSON.stringify({report_id:id,report_kind:'initial',mode:'export',...extra})});
function fixture(options={}) {
 const calls=[],report={id,patient_id:child,therapist_id:owner,publication_status:'draft',publication_revision:1,created_at:'2026-10-07T00:00:00Z',updated_at:'2026-10-07T00:00:00Z',complaint:'Вымышленная жалоба',...options.report};
 const source={parent_reports:report,parent_session_reports:report,patients:{id:child,therapist_id:owner,display_name:'Вымышленный ребёнок'},sessions:{id:report.session_id,patient_id:child,therapist_id:owner,session_date:'2026-10-07'},profiles:{id:owner,full_name:'Специалист'}};let activeCalls=0,reportReads=0;
 const client={auth:{getUser:async()=>({data:{user:options.noAuth?null:{id:owner}}})},rpc:async(name,args)=>{calls.push({name,args});if(name==='account_is_active')return {data:options.inactive||options.retired&&++activeCalls>1?false:true};if(name==='current_app_roles')return {data:[{role:options.parent?'parent':'specialist'}]};throw Error('No publication or invitation RPC allowed');},from(table){const filters=[];let columns;const q={select(v){columns=v;return q},eq(k,v){filters.push([k,v]);return q},single(){return q},maybeSingle(){return q},then(resolve,reject){return (async()=>{calls.push({table,filters,columns});if(options.denied&&table.startsWith('parent_'))return {error:Error('denied')};const row=structuredClone(source[table]);if(table.startsWith('parent_')&&columns.includes('updated_at')&&++reportReads>1&&options.changed)row.updated_at='2026-10-08';return row&&filters.every(([k,v])=>row[k]===v)?{data:row}:{error:Error('not found')};})().then(resolve,reject)}};return q},storage:{from(bucket){calls.push({bucket});return {download:async path=>{calls.push({download:path});return options.missing?{error:Error('missing')}:{data:new Blob([options.corrupt?'bad':bytes])}},createSignedUrl(){throw Error('No signed URLs')},upload(){throw Error('No storage writes')}}}}};
 const deps={env:n=>({SUPABASE_URL:'https://auth.fizira.com',SUPABASE_ANON_KEY:'anon'})[n],createClient:(url,key)=>{assert.equal(key,'anon');return client},render:async snapshot=>{calls.push({snapshot});return bytes}};
 return {handler:parentPublicationHandler('generate',deps),calls,report};
}
test('consultation export produces PDF without parent permissions or writes',async()=>{const f=fixture();const r=await f.handler(request());assert.equal(r.status,200);assert.equal(r.headers.get('content-type'),'application/pdf');assert.equal(r.headers.get('cache-control'),'no-store');assert.deepEqual(new Uint8Array(await r.arrayBuffer()),bytes);assert.equal(f.report.publication_status,'draft');assert.ok(f.calls.every(c=>!c.name||['account_is_active','current_app_roles'].includes(c.name)));});
test('foreign IDs, parent, anonymous and inactive actor are denied before rendering',async()=>{for(const [options,status] of [[{denied:true},403],[{parent:true},403],[{noAuth:true},401],[{inactive:true},403],[{report:{therapist_id:child}},403],[{report:{patient_id:id}},403]]){const f=fixture(options);assert.equal((await f.handler(request())).status,status);assert.ok(!f.calls.some(c=>c.snapshot||c.download));}for(const extra of [{patient_id:child},{pdf_path:'private/path'},{mode:'other'},{report_id:'bad'}]){const f=fixture();assert.equal((await f.handler(request(extra))).status,400);assert.equal(f.calls.length,0);}});
test('published and archived use byte-identical hashed original',async()=>{for(const publication_status of ['published','archived']){const f=fixture({report:{publication_status,published_at:'2026-10-07',pdf_storage_path:`${owner}/parent-reports/initial/${id}/1.pdf`,pdf_sha256:await digestBytes(bytes)}});const r=await f.handler(request());assert.equal(r.status,200);assert.deepEqual(new Uint8Array(await r.arrayBuffer()),bytes);assert.ok(!f.calls.some(c=>c.snapshot));}});
test('corrupt artifacts, path substitution, source/account changes fail closed',async()=>{for(const [extra,status] of [[{corrupt:true},503],[{report:{pdf_storage_path:`${child}/parent-reports/initial/${id}/1.pdf`}},403],[{changed:true},403],[{retired:true},403]]){const {report:overrides,...options}=extra;const f=fixture({...options,report:{publication_status:'published',published_at:'2026-10-07',pdf_storage_path:`${owner}/parent-reports/initial/${id}/1.pdf`,pdf_sha256:await digestBytes(bytes),...overrides}});assert.equal((await f.handler(request())).status,status);}});
test('legacy reconstruction uses frozen allowlisted text without changing history',async()=>{const frozen={schema_version:1,report_kind:'initial',revision:1,child_name:'Сохранённое имя',complaint:'Сохранённый текст'};const f=fixture({report:{publication_status:'published',published_at:'2026-10-07',published_snapshot:frozen,pdf_sha256:null}});assert.equal((await f.handler(request())).status,200);assert.equal(f.calls.find(c=>c.snapshot).snapshot.complaint,frozen.complaint);assert.deepEqual(f.report.published_snapshot,frozen);});
test('009 path reuses original, missing file normalizes unversioned frozen snapshot',async()=>{for(const missing of [false,true]){const frozen={complaint:'Только сохранённый текст'};const f=fixture({missing,report:{publication_status:'published',published_at:'2026-10-07',published_snapshot:frozen,pdf_sha256:null,pdf_storage_path:`${owner}/parent-reports/parent_reports/${id}/1.pdf`}});assert.equal((await f.handler(request())).status,200);if(missing){const s=f.calls.find(c=>c.snapshot).snapshot;assert.equal(s.schema_version,1);assert.equal(s.complaint,frozen.complaint);assert.equal(s.child_name,'');}else assert.ok(!f.calls.some(c=>c.snapshot));assert.deepEqual(f.report.published_snapshot,frozen);}});
