import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const app=readFileSync(new URL('../app.js',import.meta.url),'utf8');
const get=(name)=>{const start=app.indexOf(`function ${name}(`);assert.ok(start>=0,`${name} exists`);const end=app.indexOf('\n}\n',start)+2;return new Function(`${app.slice(start,end)};return ${name}`)();};
export const plan={main_task:'Удержание опоры при переносе веса',start_check:{action:'1. Проверить боль при опоре. 2. Оценить необходимую поддержку.',why:'Сравнить с прошлым занятием'},work_blocks:[{title:'Перенос веса у опоры',action:'Стоя у опоры специалист поддерживает таз, ребёнок переносит вес к игрушке.',why:'Контроль опоры',progress_if:'Уменьшить поддержку при устойчивом положении'}],what_to_track:['Уровень поддержки таза'],session_success_criteria:['Та же активность с меньшей поддержкой'],cautions:[],needs_review:true};
test('plan parser rejects headings without block content',async()=>{const start=app.indexOf('async function prepareNextSessionPlan('),end=app.indexOf('\nfunction buildNextSessionContext',start);const parse=new Function('callAI','validateNextSessionPlan',`${app.slice(start,end)};return prepareNextSessionPlan`)(async()=>JSON.stringify({...plan,work_blocks:[{},'Рабочий блок 2']}),get('validateNextSessionPlan'));await assert.rejects(()=>parse('fictional-child'));});
test('valid concrete plan is accepted; incomplete fields fail closed',()=>{const validate=get('validateNextSessionPlan');assert.deepEqual(validate(plan),plan);for(const invalid of [{...plan,main_task:''},{...plan,start_check:{action:''}},{...plan,work_blocks:[]},{...plan,work_blocks:[{title:'Рабочий блок 1',action:'Рабочий блок 1'}]},{...plan,what_to_track:[]},{...plan,session_success_criteria:[' '] }])assert.throws(()=>validate(invalid));});
test('draft preserves unknown tolerance and dynamics and rejects invalid enums',()=>{const validate=get('validateSessionDraft');const draft={session_note:'Работали лёжа с помощью специалиста',tolerance:null,dynamics_status:null,function_changes:'',goal_updates:[],needs_review:true};assert.deepEqual(validate(draft),draft);assert.throws(()=>validate({...draft,tolerance:'excellent'}));});
test('client and server validators accept and reject the same responses',async()=>{const edge=await import('../supabase/functions/_shared/ai-helpers.ts');for(const name of ['validateNextSessionPlan','validateSessionDraft']){const client=get(name);for(const value of [null,[],{},plan,{...plan,work_blocks:[{title:'Рабочий блок',action:''}]},{session_note:'Наблюдение',tolerance:null,dynamics_status:null,function_changes:'',goal_updates:[]}]){let a,b;try{a=client(value);}catch{a='invalid';}try{b=edge[name](value);}catch{b='invalid';}assert.deepEqual(a,b);}}});

