import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {createServer} from 'node:http';import {chromium} from 'playwright-core';
import {branch,helpers,validPlan} from './session-flow-fixture.mjs';
const root=new URL('../',import.meta.url);
test('mobile actual session flow retains editable accepted plan, reload and planned versus actual history',async()=>{
 assert.ok(process.env.CHROMIUM_EXECUTABLE,'Chromium required');const server=createServer(async(req,res)=>{try{if(req.url==='/'){res.setHeader('Content-Type','text/html');res.end('<meta name="viewport" content="width=device-width, initial-scale=1"><link rel="stylesheet" href="/styles.css"><main id="app"><div id="tabContent"></div></main>');return;}if(req.url!='/styles.css'){res.writeHead(404);res.end();return;}res.setHeader('Content-Type','text/css');res.end(await readFile(new URL('styles.css',root)));}catch{res.writeHead(500);res.end();}});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
 try{
  browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE,headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});
  const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
  const boot=async()=>page.evaluate(({branch,helpers,validPlan})=>{
   const db=JSON.parse(localStorage.getItem('synthetic-session-test')||'{"patient":{"id":"child"},"sessions":[]}');const p=structuredClone(db.patient),box=document.getElementById('tabContent');const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
   const env={window,document,box,p,state:{patientId:'child',tab:'sessions',goals:[],sessions:structuredClone(db.sessions)},user:{id:'specialist'},accountUserId:'specialist',accountRevision:1,authViewRevision:1,roleGate:{canNavigate:()=>true},accountIsCurrent:()=>true,esc,watchFormDirty(){},enableVoiceInput(){},fmtDate:x=>x,toleranceLabel:()=>'',sessionDynamicsHtml:()=>'',plannedSessionHtml:plan=>plan?`<div>План этого занятия: ${esc(plan.main_task)}</div>`:'',renderParentSessionReportEditor(){},refreshParentControls(){},SUPABASE_URL:'https://example.test',analyzeSessionDraft:async()=>({session_note:'Работа у опоры с поддержкой таза',tolerance:null,dynamics_status:null,function_changes:'',goal_updates:[]}),prepareNextSessionPlan:async()=>structuredClone(validPlan),confirm,console,flash(){},setButtonSaving:b=>b.disabled=true,setButtonError:b=>b.disabled=false,setButtonSaved:b=>b.disabled=true,sleep:async()=>{},loadPatientData:async()=>{},renderPatient(){},sb:{from(table){let payload,op;const q={update(v){payload=v;op='update';return q},insert(v){payload=v;op='insert';return q},eq(){return q},is(){return q},select(){return q},single(){return q},then(resolve){if(table==='patients')Object.assign(db.patient,payload);else if(table==='sessions'&&op==='insert')db.sessions.push({...payload,id:'s'+db.sessions.length});localStorage.setItem('synthetic-session-test',JSON.stringify(db));return Promise.resolve({data:{id:p.id},error:null}).then(resolve)}};return q}}};
   new Function('env',`with(env){${helpers}\n${branch}}`)(env);
  },{branch,helpers,validPlan});
  await page.goto(`http://127.0.0.1:${server.address().port}/`);await boot();await page.locator('#sessionTranscript').fill('Работа у опоры с поддержкой таза');await page.locator('#analyzeSessionBtn').click();await page.getByText(/Черновик подготовлен/).waitFor();assert.equal(await page.evaluate(()=>localStorage.getItem('synthetic-session-test')),null);await page.locator('#sessionSaveBtn').click();
  await page.reload();await boot();assert.equal(await page.locator('.session-history-entry').count(),1);await page.locator('#prepareNextSessionBtn').click();await page.locator('#useNextSessionPlanBtn').click();await page.locator('#acceptedSessionPlan').getByText(/План добавлен/).waitFor();assert.equal(await page.locator('[name=note]').inputValue(),'');
  await page.reload();await boot();assert.equal(await page.locator('#acceptedSessionPlan [data-plan-field=main_task]').inputValue(),validPlan.main_task);await page.locator('#acceptedSessionPlan [data-plan-field=main_task]').fill('Удержание опоры с меньшей помощью');await page.locator('#saveAcceptedPlanBtn').click();await page.getByText(/Изменения плана сохранены/).waitFor();
  const metrics=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,fields:[...document.querySelectorAll('textarea,button')].map(el=>{const r=el.getBoundingClientRect();return {left:r.left,right:r.right,width:r.width}})}));assert.ok(metrics.scroll<=390,JSON.stringify(metrics));for(const r of metrics.fields)assert.ok(r.left>=0&&r.right<=391&&r.width>0,JSON.stringify(r));
  await page.locator('[name=note]').fill('Фактически нужна прежняя помощь');await page.locator('#sessionSaveBtn').click();await page.reload();await boot();assert.equal(await page.locator('.session-history-entry').count(),2);const stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('synthetic-session-test')));assert.equal(stored.sessions[1].planned_session.main_task,'Удержание опоры с меньшей помощью');assert.equal(stored.sessions[1].note,'Фактически нужна прежняя помощь');assert.equal(stored.patient.next_session_plan,null);assert.deepEqual(errors,[]);
 }finally{if(browser)await browser.close();await new Promise(r=>server.close(r));}
});
