import test from 'node:test';
import assert from 'node:assert/strict';
import {fixture,validPlan} from './session-flow-fixture.mjs';
const click=async(h,id)=>h.document.getElementById(id).onclick();
const submit=async h=>h.document.getElementById('sessionForm').onsubmit({target:h.document.getElementById('sessionForm'),preventDefault(){}});
test('AI draft populates editable fields but does not persist until save',async()=>{const h=fixture();try{h.document.getElementById('sessionTranscript').value='Работали лёжа с помощью';await click(h,'analyzeSessionBtn');assert.match(h.document.querySelector('[name=note]').value,/лёжа/);assert.equal(h.calls.length,0);await submit(h);assert.equal(h.db.sessions.length,1);}finally{h.close();}});
test('repeated analysis cannot discard manual corrections without confirmation',async()=>{const h=fixture();try{h.document.getElementById('sessionTranscript').value='Рассказ';h.document.querySelector('[name=note]').value='Ручная правка';h.env.confirm=()=>false;await click(h,'analyzeSessionBtn');assert.equal(h.document.querySelector('[name=note]').value,'Ручная правка');}finally{h.close();}});
test('accepted plan is visible, persists after reload and snapshots separately from performed note',async()=>{const h=fixture({sessions:[{id:'old',note:'Старая запись'}]});try{await click(h,'prepareNextSessionBtn');assert.equal(h.calls.length,0);await click(h,'useNextSessionPlanBtn');assert.equal(h.p.next_session_plan.main_task,validPlan.main_task);assert.match(h.document.getElementById('acceptedSessionPlan').textContent,/План/);assert.equal(h.document.querySelector('[name=note]').value,'');h.render();assert.equal(h.document.querySelector('[data-plan-field=main_task]').value,validPlan.main_task);h.document.querySelector('[name=note]').value='Реально сделали';await submit(h);assert.equal(h.db.sessions[1].planned_session.main_task,validPlan.main_task);assert.equal(h.db.sessions[1].note,'Реально сделали');assert.equal(h.db.sessions[0].note,'Старая запись');assert.equal(h.db.patients.child.next_session_plan,null);}finally{h.close();}});
test('switched patient ignores late AI result and cannot adopt old plan',async()=>{const h=fixture();try{let resolve;h.env.prepareNextSessionPlan=()=>new Promise(r=>resolve=r);const pending=click(h,'prepareNextSessionBtn');h.state.patientId='other';resolve(validPlan);await pending;assert.equal(h.document.getElementById('useNextSessionPlanBtn'),null);assert.equal(h.calls.length,0);}finally{h.close();}});
test('manual corrections made while AI runs survive a declined overwrite',async()=>{const h=fixture();try{let resolve;h.env.analyzeSessionDraft=()=>new Promise(r=>resolve=r);h.document.getElementById('sessionTranscript').value='Рассказ';const pending=click(h,'analyzeSessionBtn');h.document.querySelector('[name=note]').value='Правка во время запроса';h.env.confirm=()=>false;resolve({session_note:'Черновик',tolerance:null,dynamics_status:null,function_changes:'',goal_updates:[]});await pending;assert.equal(h.document.querySelector('[name=note]').value,'Правка во время запроса');assert.equal(h.calls.length,0);}finally{h.close();}});
test('invalid plan is not presented as usable and leaves accepted plan intact',async()=>{const h=fixture({patient:{id:'child',next_session_plan:validPlan},plan:{...validPlan,work_blocks:[{}]}});try{await click(h,'prepareNextSessionBtn');assert.equal(h.document.getElementById('useNextSessionPlanBtn'),null);assert.match(h.document.getElementById('nextSessionPlanStatus').textContent,/неполный/);assert.deepEqual(h.p.next_session_plan,validPlan);assert.equal(h.calls.length,0);}finally{h.close();}});
test('plan save error is visible and preserves editable draft',async()=>{const h=fixture({error:{message:'offline'}});try{await click(h,'prepareNextSessionBtn');await click(h,'useNextSessionPlanBtn');assert.equal(h.p.next_session_plan,undefined);assert.match(h.document.getElementById('nextSessionPlan').textContent,/Не удалось сохранить/);assert.equal(h.document.getElementById('useNextSessionPlanBtn').disabled,false);}finally{h.close();}});
test('accepted plan edits persist without copying them into completed notes',async()=>{const h=fixture({patient:{id:'child',next_session_plan:validPlan}});try{const field=h.document.querySelector('[data-plan-field=main_task]');field.value='Изменённая задача';field.dispatchEvent(new h.window.Event('input',{bubbles:true}));h.document.querySelector('[name=note]').value='Факт';await submit(h);assert.equal(h.calls.length,0);await click(h,'saveAcceptedPlanBtn');assert.equal(h.db.patients.child.next_session_plan.main_task,'Изменённая задача');h.render();assert.equal(h.document.querySelector('[data-plan-field=main_task]').value,'Изменённая задача');assert.equal(h.document.querySelector('[name=note]').value,'');}finally{h.close();}});
test('old session editing preserves its plan and does not consume pending plan',async()=>{const oldPlan={main_task:'Старый план',work_blocks:['Наследуемый формат']};const h=fixture({patient:{id:'child',next_session_plan:validPlan},sessions:[{id:'old',note:'История',planned_session:oldPlan}]});try{h.document.querySelector('[data-edit-session]').click();h.document.querySelector('[name=note]').value='Уточнение';await submit(h);assert.deepEqual(h.db.sessions[0].planned_session,oldPlan);assert.deepEqual(h.db.patients.child.next_session_plan,validPlan);assert.equal(h.db.sessions.length,1);}finally{h.close();}});
test('patient-scoped plan never leaks when another patient form is rendered',async()=>{const a=fixture({patient:{id:'a',next_session_plan:validPlan}}),b=fixture({patient:{id:'b'}});try{assert.match(a.document.getElementById('acceptedSessionPlan').textContent,/используется/);assert.equal(b.document.getElementById('acceptedSessionPlan').textContent,'');a.state.patientId='b';await click(a,'saveAcceptedPlanBtn');assert.equal(a.calls.length,0);}finally{a.close();b.close();}});
test('legacy incomplete saved plan is warned about without data repair',()=>{const legacy={main_task:'Старая цель',work_blocks:[{},{}]};const h=fixture({patient:{id:'child',next_session_plan:legacy}});try{assert.match(h.document.getElementById('acceptedSessionPlan').textContent,/неполный/);assert.deepEqual(h.db.patients.child.next_session_plan,legacy);assert.equal(h.calls.length,0);}finally{h.close();}});

// Exact final additions. Requires click/submit/fixture/validPlan from initial session-flow test.
test('leaving the tab during session insert still consumes the captured pending plan',async()=>{let resolve;const h=fixture({patient:{id:'child',next_session_plan:validPlan},onQuery:async call=>{if(call.table==='sessions'&&call.op==='insert')await new Promise(r=>resolve=r);}});try{h.document.querySelector('[name=note]').value='Факт';const pending=submit(h);await new Promise(r=>setImmediate(r));h.state.tab='goals';resolve();await pending;assert.equal(h.db.sessions.length,1);assert.equal(h.db.patients.child.next_session_plan,null);}finally{h.close();}});
test('persisted plan updates patient memory even after leaving its tab',async()=>{let resolve;const h=fixture({onQuery:async call=>{if(call.table==='patients'&&call.op==='update')await new Promise(r=>resolve=r);}});try{await click(h,'prepareNextSessionBtn');const pending=click(h,'useNextSessionPlanBtn');await new Promise(r=>setImmediate(r));h.state.tab='goals';resolve();await pending;assert.equal(h.p.next_session_plan.main_task,validPlan.main_task);}finally{h.close();}});
test('plan fields are locked during save so later typing cannot be discarded',async()=>{let resolve;const h=fixture({patient:{id:'child',next_session_plan:validPlan},onQuery:async call=>{if(call.table==='patients'&&call.op==='update')await new Promise(r=>resolve=r);}});try{const field=h.document.querySelector('[data-plan-field=main_task]');field.value='Перед сохранением';const pending=click(h,'saveAcceptedPlanBtn');await new Promise(r=>setImmediate(r));assert.equal(field.disabled,true);resolve();await pending;assert.equal(h.document.querySelector('[data-plan-field=main_task]').value,'Перед сохранением');assert.equal(h.document.querySelector('[data-plan-field=main_task]').disabled,false);}finally{h.close();}});
test('concurrent newer plan survives consumed-plan clear and refreshes cached plan',async()=>{const newer={...validPlan,main_task:'План из другой вкладки'};const h=fixture({patient:{id:'child',next_session_plan:validPlan},onQuery:async(call,db)=>{if(call.table==='patients'&&call.op==='update'&&call.payload.next_session_plan===null)db.patients.child.next_session_plan=structuredClone(newer);}});try{h.document.querySelector('[name=note]').value='Факт';await submit(h);assert.deepEqual(h.db.sessions[0].planned_session,validPlan);assert.deepEqual(h.db.patients.child.next_session_plan,newer);assert.deepEqual(h.p.next_session_plan,newer);}finally{h.close();}});
test('zero-row plan write never claims success or overwrites another-tab plan',async()=>{const h=fixture({onQuery:async(call,db)=>{if(call.table==='patients'&&call.op==='update')db.patients.child.next_session_plan={...validPlan,main_task:'Внешний план'};}});try{await click(h,'prepareNextSessionBtn');await click(h,'useNextSessionPlanBtn');assert.equal(h.p.next_session_plan,undefined);assert.match(h.document.getElementById('nextSessionPlan').textContent,/Не удалось сохранить/);assert.equal(h.db.patients.child.next_session_plan.main_task,'Внешний план');}finally{h.close();}});

test('failed plan consumption is visible and cannot lead to a duplicate session retry',async()=>{const h=fixture({patient:{id:'child',next_session_plan:validPlan},onQuery:async call=>call.table==='patients'&&call.op==='update'?{data:null,error:{message:'offline'}}:undefined});try{h.document.querySelector('[name=note]').value='Факт';await submit(h);assert.equal(h.db.sessions.length,1);assert.match(h.document.getElementById('sessionStatus').textContent,/план.*обновите/i);assert.equal(h.document.getElementById('sessionSaveBtn').disabled,true);}finally{h.close();}});
test('transport exception before session commit leaves a visible retryable form',async()=>{let fail=true;const h=fixture({onQuery:async call=>{if(call.table==='sessions'&&fail){fail=false;throw new Error('offline');}}});try{h.document.querySelector('[name=note]').value='Факт';await submit(h);assert.equal(h.db.sessions.length,0);assert.match(h.document.getElementById('sessionStatus').textContent,/сохран|ошиб/i);assert.equal(h.document.getElementById('sessionSaveBtn').disabled,false);await submit(h);assert.equal(h.db.sessions.length,1);}finally{h.close();}});
test('account change during accepted plan save cannot install old account state',async()=>{let resolve;const h=fixture({onQuery:async call=>{if(call.table==='patients'&&call.op==='update')await new Promise(r=>resolve=r);}});try{await click(h,'prepareNextSessionBtn');const pending=click(h,'useNextSessionPlanBtn');await new Promise(r=>setImmediate(r));h.env.authViewRevision=2;h.env.accountIsCurrent=()=>false;resolve();await pending;assert.equal(h.p.next_session_plan,undefined);assert.equal(h.document.getElementById('acceptedSessionPlan').textContent,'');}finally{h.close();}});

test('adopting replacement locks both plan editors while persistence is pending',async()=>{let resolve;const h=fixture({patient:{id:'child',next_session_plan:validPlan},onQuery:async call=>{if(call.table==='patients'&&call.op==='update')await new Promise(r=>resolve=r);}});try{await click(h,'prepareNextSessionBtn');const pending=click(h,'useNextSessionPlanBtn');await new Promise(r=>setImmediate(r));assert.ok([...h.document.querySelectorAll('[data-plan-field]')].every(field=>field.disabled));resolve();await pending;}finally{h.close();}});

