-- GENERATED by node ops/security/generate-parent-portal-definition-reference.mjs
-- Offline reference from reviewed repo migrations; NEVER regenerate from live SQL.
-- Exact catalog formatting is fail-closed: engine differences require review.
-- 20260920_001_app_schema.sql sha256=2177dcc719d8c7142cc3dc4f4cc9604af8a3fb0763dd8e9e3df923d2814fad3b
-- 20260921_002_existing_target_security_fix.sql sha256=d97ce731f8eb38ac3f86ede50c1c9f83cd73eb1067406c41e37c68a7b20423f7
-- 20260921_003_patient_media_path_integrity.sql sha256=fc41e687f4a6fa18983e686b21293c69356de7dcec1ed6fe258fcb2a252ddf06
-- 20260922_004_account_deletion_jobs.sql sha256=41296c901875bb32fbe4b5414aa394d749aaa11c200a19151c20d668b61fd8ce
-- 20260923_005_specialist_schedule.sql sha256=cc46f5f913b9f36aeeaf29a9c8bfb40174f39afe2afacf096d3d87759cd97320
-- 20260923_006_schedule_calendar.sql sha256=7ccfb793023902268e19a760f9ac734ef38967424ec5ed73916f2a6702eb0135
-- 20260930_007_legal_acceptances.sql sha256=fac46d195c262584aaf20b34a9055edb5fa532d6ae3d0f1398658330061f53b9
-- 20261003_008_parent_portal_identity.sql sha256=5d2160e01d0d1a89170f616889169a78d5074d101c28710ab50803807bda2a52
-- 20261003_009_parent_portal_publications.sql sha256=01e7ae81fb2702603602c6fc40db8adde8dc5c5a4f0dfff2b5a6d7825e7979f3
-- 20261003_010_parent_publication_artifacts.sql sha256=07274cf04835b74f7b4030fc04831773d47f294efecff23f6eb8c749d3a39ea9
-- 20261003_011_parent_role_boundaries.sql sha256=3cada7dc0580566e4517ef8699511154cff957236a64d29ab2f65eb535593112
-- 20261003_012_parent_publication_archive.sql sha256=35ba78b064a0281f56a238e79bb3b38ab1f949aa74a7b72a4b1c8dae5efd4ba1
do $verify_definitions$
declare
 expected jsonb := $reviewed_reference${
  "functions": [
    {
      "name": "accept_parent_invitation",
      "signature": "accept_parent_invitation(text,jsonb)",
      "owner": "postgres",
      "definition_sha256": "b2a621e381f0e25cb4285d615ea3234fafff4431944c5a63ef8b291d4d942c38",
      "grants": [
        {
          "role": "authenticated",
          "grantable": false,
          "privilege": "EXECUTE"
        }
      ]
    },
    {
      "name": "account_is_active",
      "signature": "account_is_active()",
      "owner": "postgres",
      "definition_sha256": "4c023ee3d92769e16008c9efe293f34a06422b0de40123ef94931358444d6346",
      "grants": [
        {
          "role": "authenticated",
          "grantable": false,
          "privilege": "EXECUTE"
        }
      ]
    },
    {
      "name": "check_parent_access_owner",
      "signature": "check_parent_access_owner()",
      "owner": "postgres",
      "definition_sha256": "013e538e18c42a8780587b59bf7f6fc11152581f1c3ba93ec0ecc5186fc895e6",
      "grants": []
    },
    {
      "name": "check_parent_publication_owner",
      "signature": "check_parent_publication_owner()",
      "owner": "postgres",
      "definition_sha256": "1a9fcbfa29f4ed6226c1eb9a8c352040fc783aa2ba1b67d2108a445a5e6b6471",
      "grants": []
    },
    {
      "name": "check_parent_selected_media",
      "signature": "check_parent_selected_media()",
      "owner": "postgres",
      "definition_sha256": "8749c5ef93a27c88e48a23e0c99da7dc8bf43b6e2236968ab433ed1c03903ccc",
      "grants": []
    },
    {
      "name": "claim_parent_publication",
      "signature": "claim_parent_publication(uuid,uuid,text)",
      "owner": "postgres",
      "definition_sha256": "5930da0b893d58e599b0d5df5d7b67203d1378bc24657cc265c23313b88d8138",
      "grants": [
        {
          "role": "service_role",
          "grantable": false,
          "privilege": "EXECUTE"
        }
      ]
    },
    {
      "name": "complete_parent_publication",
      "signature": "complete_parent_publication(uuid,uuid,text,uuid,integer,text,jsonb)",
      "owner": "postgres",
      "definition_sha256": "a362bc07273f80691f2695db3934789ab566e0b99dc951d2d845e0ecf4a08d80",
      "grants": [
        {
          "role": "service_role",
          "grantable": false,
          "privilege": "EXECUTE"
        }
      ]
    },
    {
      "name": "current_app_roles",
      "signature": "current_app_roles()",
      "owner": "postgres",
      "definition_sha256": "8ab92b2039935612984fbc4454c7f2cd853735f0cba065381e27f05e9870084c",
      "grants": [
        {
          "role": "authenticated",
          "grantable": false,
          "privilege": "EXECUTE"
        }
      ]
    },
    {
      "name": "fail_parent_publication",
      "signature": "fail_parent_publication(uuid,uuid,text,uuid,integer)",
      "owner": "postgres",
      "definition_sha256": "da685925aaf55cfaebd30de55d0b2f20d3c874a65a7cc909f7ee3dca0e484975",
      "grants": [
        {
          "role": "service_role",
          "grantable": false,
          "privilege": "EXECUTE"
        }
      ]
    },
    {
      "name": "guard_parent_report_publication",
      "signature": "guard_parent_report_publication()",
      "owner": "postgres",
      "definition_sha256": "18dbd692eefbb7a5402ed57a405c4894bbeda8ef85a8205ef5ee13850d3ed683",
      "grants": []
    },
    {
      "name": "issue_parent_invitation_record",
      "signature": "issue_parent_invitation_record(uuid,uuid,uuid,text,text)",
      "owner": "postgres",
      "definition_sha256": "bd449799aaf89297ba53d155f10ba29d0700d3d2aa8b77fe461a0859dfd40435",
      "grants": [
        {
          "role": "service_role",
          "grantable": false,
          "privilege": "EXECUTE"
        }
      ]
    },
    {
      "name": "normalize_parent_contact_email",
      "signature": "normalize_parent_contact_email()",
      "owner": "postgres",
      "definition_sha256": "bff89efb2b984aec517a7276324e8a6e1e71962a3dcad264a611e8a25f862538",
      "grants": []
    },
    {
      "name": "notify_parent_goal_publication",
      "signature": "notify_parent_goal_publication()",
      "owner": "postgres",
      "definition_sha256": "1b956c00d259efc90e2ec675622c4498be24e95cbe5109a2636945e0fe41a309",
      "grants": []
    },
    {
      "name": "notify_parent_publication_or_appointment",
      "signature": "notify_parent_publication_or_appointment()",
      "owner": "postgres",
      "definition_sha256": "33894f7faabac5e15894c7a99aeb400dd16fffef3a6f22f7a7a30b47dd3f8649",
      "grants": []
    },
    {
      "name": "parent_has_active_access",
      "signature": "parent_has_active_access(uuid,uuid)",
      "owner": "postgres",
      "definition_sha256": "19966475fb6ca0e31bbc91d86160ecc99e3f5d115952f6a29adfb040a23b2559",
      "grants": [
        {
          "role": "authenticated",
          "grantable": false,
          "privilege": "EXECUTE"
        }
      ]
    },
    {
      "name": "parent_invitation_state",
      "signature": "parent_invitation_state(text)",
      "owner": "postgres",
      "definition_sha256": "6508b65c0eb4af8432458dfd643522f9e82e96a887399879c50819d80549ae87",
      "grants": [
        {
          "role": "authenticated",
          "grantable": false,
          "privilege": "EXECUTE"
        }
      ]
    },
    {
      "name": "parent_mark_notifications_read",
      "signature": "parent_mark_notifications_read(uuid[])",
      "owner": "postgres",
      "definition_sha256": "fa463e6188db7ea6ef5ea092c73294b0f6c611fb805555d4f032e0cb2437fe2c",
      "grants": [
        {
          "role": "authenticated",
          "grantable": false,
          "privilege": "EXECUTE"
        }
      ]
    },
    {
      "name": "parent_portal_children",
      "signature": "parent_portal_children()",
      "owner": "postgres",
      "definition_sha256": "55c9a93fd2e9cdaea599bd8443d44a1773e643dc20be26bcadb1dfcdf7881a68",
      "grants": [
        {
          "role": "authenticated",
          "grantable": false,
          "privilege": "EXECUTE"
        }
      ]
    },
    {
      "name": "parent_portal_dashboard",
      "signature": "parent_portal_dashboard(uuid)",
      "owner": "postgres",
      "definition_sha256": "71204626637af1588bdd65771182ae4544d9bb46cfcbf72f005fcb489a82594d",
      "grants": [
        {
          "role": "authenticated",
          "grantable": false,
          "privilege": "EXECUTE"
        }
      ]
    },
    {
      "name": "parent_portal_dynamics",
      "signature": "parent_portal_dynamics(uuid)",
      "owner": "postgres",
      "definition_sha256": "a54bb8df83b31bdf3c40783035e58e98d229ec3e0817b39627874dff634463da",
      "grants": [
        {
          "role": "authenticated",
          "grantable": false,
          "privilege": "EXECUTE"
        }
      ]
    },
    {
      "name": "parent_portal_goals",
      "signature": "parent_portal_goals(uuid)",
      "owner": "postgres",
      "definition_sha256": "e2a0dcb9b46a535e00b8d61d2af8e51172c356ece059a6d073611994596fea0b",
      "grants": [
        {
          "role": "authenticated",
          "grantable": false,
          "privilege": "EXECUTE"
        }
      ]
    },
    {
      "name": "parent_portal_notifications",
      "signature": "parent_portal_notifications(uuid)",
      "owner": "postgres",
      "definition_sha256": "693f5daebd9a2834ef2767db7ba6f7368a736f1d0616652ffd184f1d0705e092",
      "grants": [
        {
          "role": "authenticated",
          "grantable": false,
          "privilege": "EXECUTE"
        }
      ]
    },
    {
      "name": "parent_portal_report",
      "signature": "parent_portal_report(uuid)",
      "owner": "postgres",
      "definition_sha256": "be98164c05b21e7b4d96924113df4484e5b341bcf384571a4ca76c0ca0f4fd1c",
      "grants": [
        {
          "role": "authenticated",
          "grantable": false,
          "privilege": "EXECUTE"
        }
      ]
    },
    {
      "name": "parent_portal_reports",
      "signature": "parent_portal_reports(uuid)",
      "owner": "postgres",
      "definition_sha256": "280f8efc538135908bcb401878f66eed23915bcb1b75629ba4e2502b56838383",
      "grants": [
        {
          "role": "authenticated",
          "grantable": false,
          "privilege": "EXECUTE"
        }
      ]
    },
    {
      "name": "parent_portal_schedule",
      "signature": "parent_portal_schedule(uuid,text)",
      "owner": "postgres",
      "definition_sha256": "4ad8f4f40d35c22b2212551007c3bb137a51195b137455ece5f256b2f299fdf7",
      "grants": [
        {
          "role": "authenticated",
          "grantable": false,
          "privilege": "EXECUTE"
        }
      ]
    },
    {
      "name": "parent_report_projection",
      "signature": "parent_report_projection(uuid)",
      "owner": "postgres",
      "definition_sha256": "0aab9976fdd6865f647356afab9438db8d423b000d17a0965f181341a7c3844a",
      "grants": []
    },
    {
      "name": "parent_storage_write_allowed",
      "signature": "parent_storage_write_allowed(text,text)",
      "owner": "postgres",
      "definition_sha256": "772a6e3d8a257260203655f7835db814542b72ba30ec436788a8215eae182954",
      "grants": [
        {
          "role": "authenticated",
          "grantable": false,
          "privilege": "EXECUTE"
        },
        {
          "role": "service_role",
          "grantable": false,
          "privilege": "EXECUTE"
        }
      ]
    },
    {
      "name": "preserve_prior_parent_consent",
      "signature": "preserve_prior_parent_consent()",
      "owner": "postgres",
      "definition_sha256": "c399398d382c93423032a58086e49ad51d050f5a464721b420c1c6f317c9ef71",
      "grants": []
    },
    {
      "name": "provision_ordinary_specialist",
      "signature": "provision_ordinary_specialist()",
      "owner": "postgres",
      "definition_sha256": "071907d761de703db81ba591424e209174ff07e2a28bd5c041c803302ea9b106",
      "grants": []
    },
    {
      "name": "reject_parent_consent_audit_mutation",
      "signature": "reject_parent_consent_audit_mutation()",
      "owner": "postgres",
      "definition_sha256": "49b134cbdbbc06e2f8aec85efa8cf29debbb9c1272246e6c6657e5ad85bb007d",
      "grants": []
    },
    {
      "name": "reserve_parent_signup",
      "signature": "reserve_parent_signup()",
      "owner": "postgres",
      "definition_sha256": "a072b7715c3c31fbcbf7a22d18992bba756e1ae199f9b0495a14da633bb98be7",
      "grants": []
    },
    {
      "name": "resolve_parent_publication_file",
      "signature": "resolve_parent_publication_file(uuid,uuid,text,uuid)",
      "owner": "postgres",
      "definition_sha256": "bedfc7088130280a24281391087bab91fd4756af0a1f9e49077bc41050d42872",
      "grants": [
        {
          "role": "service_role",
          "grantable": false,
          "privilege": "EXECUTE"
        }
      ]
    },
    {
      "name": "revoke_parent_access_record",
      "signature": "revoke_parent_access_record(uuid,uuid)",
      "owner": "postgres",
      "definition_sha256": "2936b955866f73321958d7820c54e9d4520f5f477562ba48b92b5b918da14476",
      "grants": [
        {
          "role": "service_role",
          "grantable": false,
          "privilege": "EXECUTE"
        }
      ]
    },
    {
      "name": "specialist_source_access",
      "signature": "specialist_source_access()",
      "owner": "postgres",
      "definition_sha256": "ff39aef14aa8ebdc590e3806a9af9ca8c926908a9a2c582644047f3b9bec4f27",
      "grants": [
        {
          "role": "authenticated",
          "grantable": false,
          "privilege": "EXECUTE"
        },
        {
          "role": "service_role",
          "grantable": false,
          "privilege": "EXECUTE"
        }
      ]
    },
    {
      "name": "specialist_storage_access",
      "signature": "specialist_storage_access(text)",
      "owner": "postgres",
      "definition_sha256": "2ef1ec1e8b73067042db99681cecf68e646a173e7336016ff086c022c6282e81",
      "grants": [
        {
          "role": "authenticated",
          "grantable": false,
          "privilege": "EXECUTE"
        },
        {
          "role": "service_role",
          "grantable": false,
          "privilege": "EXECUTE"
        }
      ]
    }
  ],
  "policies": [
    {
      "schemaname": "public",
      "tablename": "app_user_roles",
      "policyname": "app_user_roles_select_own",
      "permissive": "PERMISSIVE",
      "roles": [
        "authenticated"
      ],
      "cmd": "SELECT",
      "qual": "(user_id = auth.uid())",
      "with_check": null
    },
    {
      "schemaname": "public",
      "tablename": "legal_document_versions",
      "policyname": "legal_document_versions_select_current",
      "permissive": "PERMISSIVE",
      "roles": [
        "authenticated"
      ],
      "cmd": "SELECT",
      "qual": "is_active",
      "with_check": null
    },
    {
      "schemaname": "public",
      "tablename": "parent_child_access",
      "policyname": "parent_child_access_specialist_select",
      "permissive": "PERMISSIVE",
      "roles": [
        "authenticated"
      ],
      "cmd": "SELECT",
      "qual": "((therapist_id = auth.uid()) AND (EXISTS ( SELECT 1\n   FROM app_user_roles r\n  WHERE ((r.user_id = auth.uid()) AND (r.role = 'specialist'::text)))) AND (EXISTS ( SELECT 1\n   FROM patients p\n  WHERE ((p.id = parent_child_access.patient_id) AND (p.therapist_id = auth.uid())))))",
      "with_check": null
    },
    {
      "schemaname": "public",
      "tablename": "parent_goal_publications",
      "policyname": "account_must_be_active",
      "permissive": "RESTRICTIVE",
      "roles": [
        "authenticated"
      ],
      "cmd": "ALL",
      "qual": "account_is_active()",
      "with_check": "account_is_active()"
    },
    {
      "schemaname": "public",
      "tablename": "parent_goal_publications",
      "policyname": "specialist_own",
      "permissive": "PERMISSIVE",
      "roles": [
        "authenticated"
      ],
      "cmd": "ALL",
      "qual": "((therapist_id = auth.uid()) AND (EXISTS ( SELECT 1\n   FROM app_user_roles r\n  WHERE ((r.user_id = auth.uid()) AND (r.role = 'specialist'::text)))) AND (EXISTS ( SELECT 1\n   FROM patients p\n  WHERE ((p.id = parent_goal_publications.patient_id) AND (p.therapist_id = auth.uid())))))",
      "with_check": "((therapist_id = auth.uid()) AND (EXISTS ( SELECT 1\n   FROM app_user_roles r\n  WHERE ((r.user_id = auth.uid()) AND (r.role = 'specialist'::text)))) AND (EXISTS ( SELECT 1\n   FROM patients p\n  WHERE ((p.id = parent_goal_publications.patient_id) AND (p.therapist_id = auth.uid())))))"
    },
    {
      "schemaname": "public",
      "tablename": "parent_invitations",
      "policyname": "parent_invitations_specialist_select",
      "permissive": "PERMISSIVE",
      "roles": [
        "authenticated"
      ],
      "cmd": "SELECT",
      "qual": "((therapist_id = auth.uid()) AND (EXISTS ( SELECT 1\n   FROM app_user_roles r\n  WHERE ((r.user_id = auth.uid()) AND (r.role = 'specialist'::text)))) AND (EXISTS ( SELECT 1\n   FROM patients p\n  WHERE ((p.id = parent_invitations.patient_id) AND (p.therapist_id = auth.uid())))))",
      "with_check": null
    },
    {
      "schemaname": "public",
      "tablename": "parent_notifications",
      "policyname": "account_must_be_active",
      "permissive": "RESTRICTIVE",
      "roles": [
        "authenticated"
      ],
      "cmd": "ALL",
      "qual": "account_is_active()",
      "with_check": "account_is_active()"
    },
    {
      "schemaname": "public",
      "tablename": "parent_notifications",
      "policyname": "specialist_own",
      "permissive": "PERMISSIVE",
      "roles": [
        "authenticated"
      ],
      "cmd": "SELECT",
      "qual": "((therapist_id = auth.uid()) AND (EXISTS ( SELECT 1\n   FROM app_user_roles r\n  WHERE ((r.user_id = auth.uid()) AND (r.role = 'specialist'::text)))) AND (EXISTS ( SELECT 1\n   FROM patients p\n  WHERE ((p.id = parent_notifications.patient_id) AND (p.therapist_id = auth.uid())))))",
      "with_check": null
    },
    {
      "schemaname": "public",
      "tablename": "parent_reports",
      "policyname": "account_must_be_active",
      "permissive": "RESTRICTIVE",
      "roles": [
        "authenticated"
      ],
      "cmd": "ALL",
      "qual": "account_is_active()",
      "with_check": "account_is_active()"
    },
    {
      "schemaname": "public",
      "tablename": "parent_reports",
      "policyname": "parent_reports_delete_own",
      "permissive": "PERMISSIVE",
      "roles": [
        "authenticated"
      ],
      "cmd": "DELETE",
      "qual": "(therapist_id = auth.uid())",
      "with_check": null
    },
    {
      "schemaname": "public",
      "tablename": "parent_reports",
      "policyname": "parent_reports_insert_own",
      "permissive": "PERMISSIVE",
      "roles": [
        "authenticated"
      ],
      "cmd": "INSERT",
      "qual": null,
      "with_check": "((therapist_id = auth.uid()) AND (EXISTS ( SELECT 1\n   FROM patients p\n  WHERE ((p.id = parent_reports.patient_id) AND (p.therapist_id = auth.uid())))))"
    },
    {
      "schemaname": "public",
      "tablename": "parent_reports",
      "policyname": "parent_reports_select_own",
      "permissive": "PERMISSIVE",
      "roles": [
        "authenticated"
      ],
      "cmd": "SELECT",
      "qual": "(therapist_id = auth.uid())",
      "with_check": null
    },
    {
      "schemaname": "public",
      "tablename": "parent_reports",
      "policyname": "parent_reports_update_own",
      "permissive": "PERMISSIVE",
      "roles": [
        "authenticated"
      ],
      "cmd": "UPDATE",
      "qual": "(therapist_id = auth.uid())",
      "with_check": "((therapist_id = auth.uid()) AND (EXISTS ( SELECT 1\n   FROM patients p\n  WHERE ((p.id = parent_reports.patient_id) AND (p.therapist_id = auth.uid())))))"
    },
    {
      "schemaname": "public",
      "tablename": "parent_reports",
      "policyname": "specialist_role_required",
      "permissive": "RESTRICTIVE",
      "roles": [
        "authenticated"
      ],
      "cmd": "ALL",
      "qual": "specialist_source_access()",
      "with_check": "specialist_source_access()"
    },
    {
      "schemaname": "public",
      "tablename": "parent_session_report_media",
      "policyname": "account_must_be_active",
      "permissive": "RESTRICTIVE",
      "roles": [
        "authenticated"
      ],
      "cmd": "ALL",
      "qual": "account_is_active()",
      "with_check": "account_is_active()"
    },
    {
      "schemaname": "public",
      "tablename": "parent_session_report_media",
      "policyname": "specialist_own",
      "permissive": "PERMISSIVE",
      "roles": [
        "authenticated"
      ],
      "cmd": "ALL",
      "qual": "((therapist_id = auth.uid()) AND (EXISTS ( SELECT 1\n   FROM app_user_roles r\n  WHERE ((r.user_id = auth.uid()) AND (r.role = 'specialist'::text)))) AND (EXISTS ( SELECT 1\n   FROM patients p\n  WHERE ((p.id = parent_session_report_media.patient_id) AND (p.therapist_id = auth.uid())))))",
      "with_check": "((therapist_id = auth.uid()) AND (EXISTS ( SELECT 1\n   FROM app_user_roles r\n  WHERE ((r.user_id = auth.uid()) AND (r.role = 'specialist'::text)))) AND (EXISTS ( SELECT 1\n   FROM patients p\n  WHERE ((p.id = parent_session_report_media.patient_id) AND (p.therapist_id = auth.uid())))))"
    },
    {
      "schemaname": "public",
      "tablename": "parent_session_reports",
      "policyname": "account_must_be_active",
      "permissive": "RESTRICTIVE",
      "roles": [
        "authenticated"
      ],
      "cmd": "ALL",
      "qual": "account_is_active()",
      "with_check": "account_is_active()"
    },
    {
      "schemaname": "public",
      "tablename": "parent_session_reports",
      "policyname": "specialist_own",
      "permissive": "PERMISSIVE",
      "roles": [
        "authenticated"
      ],
      "cmd": "ALL",
      "qual": "((therapist_id = auth.uid()) AND (EXISTS ( SELECT 1\n   FROM app_user_roles r\n  WHERE ((r.user_id = auth.uid()) AND (r.role = 'specialist'::text)))) AND (EXISTS ( SELECT 1\n   FROM patients p\n  WHERE ((p.id = parent_session_reports.patient_id) AND (p.therapist_id = auth.uid())))))",
      "with_check": "((therapist_id = auth.uid()) AND (EXISTS ( SELECT 1\n   FROM app_user_roles r\n  WHERE ((r.user_id = auth.uid()) AND (r.role = 'specialist'::text)))) AND (EXISTS ( SELECT 1\n   FROM patients p\n  WHERE ((p.id = parent_session_reports.patient_id) AND (p.therapist_id = auth.uid())))))"
    }
  ]
}$reviewed_reference$::jsonb;
 actual jsonb;
 names text[];
 tables text[] := array['app_user_roles','legal_document_versions','parent_child_access','parent_invitations','parent_consent_audit','parent_signup_reservations','parent_reports','parent_session_reports','parent_session_report_media','parent_goal_publications','parent_notifications'];
begin
 select array_agg(value->>'name') into names from jsonb_array_elements(expected->'functions');
 select coalesce(jsonb_agg(to_jsonb(definition)),'[]'::jsonb) into actual from (
 select p.proname name, p.oid::regprocedure::text signature, pg_get_userbyid(p.proowner) owner,
 encode(sha256(convert_to(pg_get_functiondef(p.oid),'UTF8')),'hex') definition_sha256,
 coalesce((select jsonb_agg(jsonb_build_object('role',case when a.grantee=0 then 'PUBLIC' else pg_get_userbyid(a.grantee) end,'privilege',a.privilege_type,'grantable',a.is_grantable) order by case when a.grantee=0 then 'PUBLIC' else pg_get_userbyid(a.grantee) end collate "C",a.privilege_type,a.is_grantable)
 from aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) a where a.grantee<>p.proowner),'[]'::jsonb) grants
 from pg_proc p where p.pronamespace='public'::regnamespace and p.proname=any(names) order by p.proname collate "C",p.oid::regprocedure::text collate "C"
 ) definition;
 if actual is distinct from expected->'functions' then
  raise exception 'STOP: unreviewed parent security function definition/grants drift';
 end if;
 select coalesce(jsonb_agg(to_jsonb(definition)),'[]'::jsonb) into actual from (
 select schemaname,tablename,policyname,permissive,roles,cmd,qual,with_check
 from pg_policies where schemaname='public' and tablename=any(tables)
 order by tablename collate "C",policyname collate "C"
 ) definition;
 if actual is distinct from expected->'policies' then
  raise exception 'STOP: unreviewed parent publication/identity policy set or definition drift';
 end if;
end; $verify_definitions$;
